In [1]:
#import data
import pandas as pd

filename = 'datasets/articles_data_homeproject.csv'

#read a CSV file with pandas
df = pd.read_csv(filename)

In [2]:
df.head()

,Unnamed: 0,source_id,source_name,author,title,description,url,url_to_image,published_at,content,top_article,engagement_reaction_count,engagement_comment_count,engagement_share_count,engagement_comment_plugin_count
0,0,reuters,Reuters,Reuters Editorial,NTSB says Autopilot engaged in 2018 California...,The National Transportation Safety Board said ...,https://www.reuters.com/article/us-tesla-crash...,https://s4.reutersmedia.net/resources/r/?m=02&...,2019-09-03T16:22:20Z,WASHINGTON (Reuters) - The National Transporta...,0.0,0.0,0.0,2528.0,0.0
1,1,the-irish-times,The Irish Times,Eoin Burke-Kennedy,Unemployment falls to post-crash low of 5.2%,Latest monthly figures reflect continued growt...,https://www.irishtimes.com/business/economy/un...,https://www.irishtimes.com/image-creator/?id=1...,2019-09-03T10:32:28Z,The States jobless rate fell to 5.2 per cent l...,0.0,6.0,10.0,2.0,0.0
2,2,the-irish-times,The Irish Times,Deirdre McQuillan,"Louise Kennedy AW2019: Long coats, sparkling t...",Autumn-winter collection features designer’s g...,https://www.irishtimes.com/\t\t\t\t\t\t\t/life...,https://www.irishtimes.com/image-creator/?id=1...,2019-09-03T14:40:00Z,Louise Kennedy is showing off her autumn-winte...,1.0,NaN,NaN,NaN,NaN
3,3,al-jazeera-english,Al Jazeera English,Al Jazeera,North Korean footballer Han joins Italian gian...,Han is the first North Korean player in the Se...,https://www.aljazeera.com/news/2019/09/north-k...,https://www.aljazeera.com/mritems/Images/2019/...,2019-09-03T17:25:39Z,"Han Kwang Song, the first North Korean footbal...",0.0,0.0,0.0,7.0,0.0
4,4,bbc-news,BBC News,BBC News,UK government lawyer says proroguing parliamen...,"The UK government's lawyer, David Johnston arg...",https://www.bbc.co.uk/news/av/uk-scotland-4956...,https://ichef.bbci.co.uk/news/1024/branded_new...,2019-09-03T14:39:21Z,NaN,0.0,0.0,0.0,0.0,0.0

In [3]:
df['source_name'].value_counts()

Reuters                    1252
BBC News                   1242
The Irish Times            1232
ABC News                   1139
CNN                        1132
Business Insider           1048
The New York Times          986
CBS News                    952
Newsweek                    539
Al Jazeera English          499
The Wall Street Journal     333
ESPN                         82
460.0                         1
Name: source_name, dtype: int64

In [15]:
df['author'].value_counts().head(15)

The Associated Press                975
Reuters Editorial                   685
CBS News                            637
https://www.facebook.com/bbcnews    533
Al Jazeera                          312
The Irish Times                     255
BBC News                            201
CBS/AP                               69
Dan Cancian                          45
AP                                   35
Lisa Respers France, CNN             30
Brendan Cole                         29
Ewan Palmer                          27
Thomson Reuters                      25
David Brennan                        24
Name: author, dtype: int64